### PR TITLE
conjugate gradient on GPU

### PR DESCRIPTION
**Pull request by anoopkcn**
### Description of the Pull Request (PR)
ccgdiagg conjugate gradient(CG) subroutine in the ccgdiagg.f90 is mainly a single file residing subroutine called by diag_bands_k subroutine in the c_bands.f90 file. 
The ccgdiagg calls 5 functions namely ddot, s_1psi, h_1psi, ZGEMV and mp_sum
In the GPU version of the subroutine above functions are replaced by the following functions cgDdot which is an in-file function calling the  cublasDdot function for dot-product between 2 vectors.
s_1psi and h_1psi which applies S and H to a single wave function is replaced with s_psi and h_psi with appropriate arguments.
mp_sum for complex vector is implemented in the mp.f90 file.
Along with the use of cuf kernels makes the cg method significantly faster than the cpu counterpart(todo: benchmarks)

### This fixes or addresses the following GitHub issues

- Ref: #25

### CODE REVIEW

**Comment by fspiga** [comment]
Thank you Anoop! We need to tag a version before merge this into the branch `features/cg`. Please make sure you eventually continue to update your `devel-gpu-cg` branch going forward and the PR will reflect changes.

**Review by maxcuda — CHANGES_REQUESTED** [review]
These changes are not needed ( there is already an interface for cublas functions in the PGI compiler).
Please remove these two files.

**Comment by romerojosh** [comment]
Hey Anoop,
What cases have you been able to run your current devel-gpu-cg build successfully? I just tried running your build on AUSURF112 with 2 GPUs and it is failing on the first iteration. It looks like it is getting into the CG loop but a call to zhegvdx_gpu after is erroring out, indicating that something is wrong. Some output:
```
Self-consistent Calculation

     iteration #  1     ecut=    25.00 Ry     beta=0.70
     CG style diagonalization
 zhegvdx_gpu error: cusolverDnZpotrf failed!

 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
     Error in routine cdiaghg (1):
     incorrect call to ZHEGV*
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

     stopping ...
```
This is using commit cd6b774405baa0494c735c78b4a855478394a006 in your forked repository. Please let me know if you are able to run this case correctly. Went ahead and uploaded my input and pseudo files though I think you already have them for this case.


[AUSURF112.zip](https://github.com/RSE-Cambridge/qe-gpu/files/1315515/AUSURF112.zip)

**Comment by fspiga** [comment]
I notice `ccgdiagg.f90` has the `f90` extension rather than `F90`. Check how `make.inc` handles various file extensions and check `cdiaghg.F90` how the two-step compilation is handled.

**Comment by romerojosh** [comment]
The .f90 extension is fine. cdiaghg.F90 actually doesn't need to be compiled twice actually since it doesn't use an overloaded interface. ccgdiagg.f90 doesn't use one yet either.

**Comment by anoopkcn** [comment]
@romerojosh The recent commits should fix the `zhegvdx_gpu error: cusolverDnZpotrf failed!` error. It was due to an improper call to s_psi. Now it should behave as expected

**Comment by fspiga** [comment]
@strivetobelazy have you push everything? I got this from my local CI system

```
mpif90 -pgf90libs  -mp -Mcuda=cc60,cuda8.0 -Mlarge_arrays -o pw.x \
   pwscf.o  libpw.a ../../Modules/libqemod.a ../../FFTXlib/libqefft.a ../../LAXlib/libqela.a /home/fspiga/anoop/qe-gpu//clib/clib.a /home/fspiga/anoop/qe-gpu//iotk/src/libiotk.a -L/opt/intel/compilers_and_libraries_2017.4.196/linux/mkl/lib/intel64 -lmkl_intel_lp64 -pgf90libs -lmkl_core -lmkl_pgi_thread -Mcudalib=cufft,cublas,cusolver /home/fspiga/anoop/qe-gpu//EIGENSOLVER_GPU/lib_eigsolve/lib_eigsolve.a
ptxas info    : 'device-function-maxrregcount' is a BETA feature
ptxas info    : 'device-function-maxrregcount' is a BETA feature
ptxas info    : 'device-function-maxrregcount' is a BETA feature
ptxas info    : 'device-function-maxrregcount' is a BETA feature
ptxas info    : 'device-function-maxrregcount' is a BETA feature
ptxas info    : 'device-function-maxrregcount' is a BETA feature
ptxas info    : 'device-function-maxrregcount' is a BETA feature
ptxas info    : 'device-function-maxrregcount' is a BETA feature
ptxas info    : 'device-function-maxrregcount' is a BETA feature
ptxas info    : 'device-function-maxrregcount' is a BETA feature
ptxas info    : 'device-function-maxrregcount' is a BETA feature
ptxas info    : 'device-function-maxrregcount' is a BETA feature
ptxas info    : 'device-function-maxrregcount' is a BETA feature
ptxas info    : 'device-function-maxrregcount' is a BETA feature
ptxas info    : 'device-function-maxrregcount' is a BETA feature
ptxas info    : 'device-function-maxrregcount' is a BETA feature
ptxas info    : 'device-function-maxrregcount' is a BETA feature
ptxas info    : 'device-function-maxrregcount' is a BETA feature
ptxas info    : 'device-function-maxrregcount' is a BETA feature
ptxas info    : 'device-function-maxrregcount' is a BETA feature
ptxas info    : 'device-function-maxrregcount' is a BETA feature
ptxas info    : 'device-function-maxrregcount' is a BETA feature
ptxas info    : 'device-function-maxrregcount' is a BETA feature
ptxas info    : 'device-function-maxrregcount' is a BETA feature
ptxas info    : 'device-function-maxrregcount' is a BETA feature
ptxas info    : 'device-function-maxrregcount' is a BETA feature
ptxas info    : 'device-function-maxrregcount' is a BETA feature
ptxas info    : 'device-function-maxrregcount' is a BETA feature
ptxas info    : 'device-function-maxrregcount' is a BETA feature
ptxas info    : 'device-function-maxrregcount' is a BETA feature
ptxas info    : 'device-function-maxrregcount' is a BETA feature
libpw.a(ccgdiagg.o): In function `ccgdiagg_':
/home/fspiga/anoop/qe-gpu/PW/src/./ccgdiagg.f90:171: undefined reference to `s_1psi_gpu_'
/home/fspiga/anoop/qe-gpu/PW/src/./ccgdiagg.f90:235: undefined reference to `h_1psi_gpu_'
/home/fspiga/anoop/qe-gpu/PW/src/./ccgdiagg.f90:275: undefined reference to `s_1psi_gpu_'
/home/fspiga/anoop/qe-gpu/PW/src/./ccgdiagg.f90:367: undefined reference to `h_1psi_gpu_'
pgacclnk: child process exit status 1: /usr/bin/ld
make[2]: *** [pw.x] Error 2
make[2]: Leaving directory `/home/fspiga/anoop/qe-gpu/PW/src'
make[1]: *** [pw] Error 1
make[1]: Leaving directory `/home/fspiga/anoop/qe-gpu/PW'
make: *** [pw] Error 1
```

**Comment by anoopkcn** [comment]
@fspiga It is due to the case sensitivity of the h_1psi.f90 and s_1psi.f90 this should be h_1psi.F90 and h_1psi.F90. Somehow my git push doesn't recognize the case change in the file name.

**Comment by fspiga** [comment]
`git mv` does not work? Are you making the commits from a Windows or OSX machine?

**Comment by anoopkcn** [comment]
OSX, but I forgot to do  `git mv`, I just did a mv. I made the changes now. They should be with their proper names.

**Comment by romerojosh** [comment]
There is a missing dependency which disables parallel compilation. Need to add the following line to `PW/src/make.depend`:
``` ccgdiagg.o : cpu_gpu_interface.o ```

**Comment by anoopkcn** [comment]
@romerojosh  It has been added to the make.depend

**Comment by fspiga** [comment]
@strivetobelazy while ago I did these tests using AUSURF112 on my workstation (8-core Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz and 2 Quadro P100. I used PGI 17.7 and Intel MKL 2017.0.3)

```
CG CPU ( 4 MPI x 2 OMP ): 3376.72
CG CPU ( 8 MPI x 1 OMP ): 3207.86

CG GPU ( 2 MPI x 2 OMP + 2 GP100 ): 744.99 [ 4.3x vs best CPU ]
0320917033804, 23769, 44 %, 8035 MiB, 748045 ms
0320317019540, 23770, 39 %, 8045 MiB, 748299 ms


DAVID CPU ( 4 MPI x 2 OMP ): 607.41
DAVID CPU ( 8 MPI x 1 OMP ): 521.80

DAVID GPU ( 2 MPI x 2 OMP + 2 GP100 ): 91.56 [ 5.7x vs best CPU ]
0320917033804, 2826, 20 %, 13387 MiB, 94659 ms
0320317019540, 2827, 17 %, 13393 MiB, 94940 ms
```
(timestamp, pid, GPU utilization, memory, GPU time)

CG is by default slow so I am not surprised that compared to Davidson it takes much longer time. Interesting nvdriver accounting shows higher average utilization of the GPU in case of CG that Davidson. Memory footprint of CG on GPU is lower than Davidson (as expected).

Recent modifications have made some allocations persistent (psi_d, hpsi_d, spsi_d) within a module. Have a look, adopting such strategies in the CG case is likely lower than what it seems. 

There are definitely some places for improvement:
- Lots of places where loops can be combined to reduce the number of distinct CUF kernels to save memory bandwidth and reduce latency losses. 
- There also appears to be a lot of parallel reductions using mp_sum during the CG iteration, which could be slowing things down quite a bit. Looks like the CG code by default attempts to distribute the CG iteration across several processes (`intra_bgrp_comm`), but it might be a better solution to limit to a single GPU since I don't think there is really a lot of work within each individual CG computation to begin with. Unsure what the difficulty of changing this would be.

Before merging the code, we suggest to more on these aspects and keep pushing changes in the same branch so the PR is updated.

**Pull request closed without merging**
